spring.application.name=EPLPlayers

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://eplplayers-db.ck7ku4qwqy3f.us-east-1.rds.amazonaws.com:5432/pl_data}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123Tienlen!123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/documentation